#!/usr/bin/env node
/**
 * Regenerates `src/abi/*.ts` from the canonical ABI exports in `packages/abi`.
 *
 * The generated files are committed: the web app is a standalone npm project and must build
 * without the contracts workspace present. Re-run this after any contract ABI change:
 *
 *     npm run sync:abi
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs'
import { join, dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const webRoot = resolve(here, '..')
const abiSrc = resolve(webRoot, '..', 'packages', 'abi')
const outDir = join(webRoot, 'src', 'abi')

if (!existsSync(abiSrc)) {
  console.error(`[sync-abi] not found: ${abiSrc}\n` + `Run this from inside the updown-bnb monorepo checkout.`)
  process.exit(1)
}

const lowerFirst = (s) => s.charAt(0).toLowerCase() + s.slice(1)

let count = 0
for (const file of readdirSync(abiSrc).filter((f) => f.endsWith('.json')).sort()) {
  const name = file.replace(/\.json$/, '')
  const abi = JSON.parse(readFileSync(join(abiSrc, file), 'utf8'))
  const body = [
    `// AUTO-GENERATED by scripts/sync-abi.mjs from packages/abi/${file} — do not edit by hand.`,
    `export const ${lowerFirst(name)}Abi = ${JSON.stringify(abi, null, 2)} as const`,
    '',
  ].join('\n')
  writeFileSync(join(outDir, `${name}.ts`), body)
  count++
}
console.log(`[sync-abi] wrote ${count} ABI module(s) to src/abi/`)
