#!/usr/bin/env node
// Run after `cd contracts && forge build`; web builds use the committed TS output.
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../../', import.meta.url))
const names = ['RelayAggregator', 'TestUSDT', 'UpDownMarketERC20', 'UpDownRegistry']
// Read all inputs before writing, so a missing artifact cannot leave a partial update.
const outputs = names.map((name) => {
  const source = `contracts/out/${name}.sol/${name}.json`
  const { abi } = JSON.parse(readFileSync(resolve(root, source), 'utf8'))
  if (!Array.isArray(abi) || !abi.length) throw new Error(`Missing ABI in ${source}; run forge build first`)
  return [name, `// AUTO-GENERATED by scripts/sync-abi.mjs from ${source} — do not edit by hand.\n` +
    `export const ${name[0].toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(abi, null, 2)} as const\n`]
})
for (const [name, body] of outputs) writeFileSync(resolve(root, `web/src/abi/${name}.ts`), body)
console.log(`[sync-abi] wrote ${outputs.length} modules from compiled contracts`)
